version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 8085:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.16.5
      FORGE_VERSION: 36.2.34
    volumes:
      - ./mcdata:/data
    tty: true
    stdin_open: true
    restart: unless-stopped