version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 8085:25565
      - 8086:25575
    environment:
      EULA: "TRUE"
      MOTD: "This MCServer is running on a docker-compose!!"
      TYPE: "FORGE"
      VERSION: 1.10.2
      #FORGE_VERSION: 12.18.3.2511
      MEMORY: 16G

      OVERRIDE_WHITELIST: "TRUE"
      WHITELIST_FILE: /extra/whitelist.json

      #MODS_FILE: /extras/mods.txt
      #REMOVE_OLD_MODS: "TRUE"

    volumes:
      - ./mcdata:/data
      - ./whitelist.json:/extra/whitelist.json:ro
      - ./mods.txt:/extras/mods.txt:ro
    tty: true
    stdin_open: true
    restart: unless-stopped
